### ISSUE TITLE
NHI Numbers are Changing

### ISSUE THREAD

**Issue by rscottweekly** [mcshaz/PicuDrugsClient#40]
Hi Brent - didn't think it was worth doing a PR for this. Love your work. 

NHI Number allocations are changing - see https://www.health.govt.nz/our-work/health-identity/national-health-index/upcoming-changes-nhi-numbers

To fix this you can change your regex to 
`([A-HJ-NP-Z]{3}\d{4}|[A-HJ-NP-Z]{3}\d{2}[A-HJ-NP-Z]{2}|SIM00\d{2})` in validators.ts 

I haven't updated the Checksum stuff - can look at that if its helpful?

**Comment by mcshaz** [comment]
thank you very much
